"""

Revision ID: 11b90abc3fd1
Revises: 144f7d62608b
Create Date: 2025-12-21 17:59:19.711126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b90abc3fd1'
down_revision: Union[str, Sequence[str], None] = '144f7d62608b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residential_complex', sa.Column('kz_description', sa.String(), nullable=True))
    op.add_column('residential_complex', sa.Column('en_description', sa.String(), nullable=True))
    op.add_column('residential_complex', sa.Column('ru_description', sa.String(), nullable=True))
    op.add_column('residential_complex', sa.Column('ru_short_description', sa.String(length=300), nullable=True))
    op.add_column('residential_complex', sa.Column('kz_short_description', sa.String(length=300), nullable=True))
    op.add_column('residential_complex', sa.Column('en_short_description', sa.String(length=300), nullable=True))
    op.drop_column('residential_complex', 'description')
    op.drop_column('residential_complex', 'short_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residential_complex', sa.Column('short_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('residential_complex', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('residential_complex', 'en_short_description')
    op.drop_column('residential_complex', 'kz_short_description')
    op.drop_column('residential_complex', 'ru_short_description')
    op.drop_column('residential_complex', 'ru_description')
    op.drop_column('residential_complex', 'en_description')
    op.drop_column('residential_complex', 'kz_description')
    # ### end Alembic commands ###
