"""Fix panorama foreign keys

Revision ID: 144f7d62608b
Revises: 77bfaf0fc019
Create Date: 2025-12-21 08:24:32.789540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144f7d62608b'
down_revision: Union[str, Sequence[str], None] = '77bfaf0fc019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panoramas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residential_complex_id', sa.Integer(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE_360', 'VIDEO_360', 'AR_MODEL', name='panoramatype'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.ForeignKeyConstraint(['residential_complex_id'], ['residential_complex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panoramas_id'), 'panoramas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_panoramas_id'), table_name='panoramas')
    op.drop_table('panoramas')
    # ### end Alembic commands ###
