"""add_image_url_to_promotions

Revision ID: 77bfaf0fc019
Revises: 1232bc02a48f
Create Date: 2025-12-19 14:14:41.630992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77bfaf0fc019'
down_revision: Union[str, Sequence[str], None] = '1232bc02a48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('review', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('review', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('promotions', 'image_url')
    # ### end Alembic commands ###
