"""

Revision ID: 8189fa6e13cb
Revises: 6685e8d8adda
Create Date: 2025-10-02 13:02:39.372667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8189fa6e13cb'
down_revision: Union[str, Sequence[str], None] = '6685e8d8adda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residential_complex', sa.Column('apartment_area', sa.DECIMAL(), nullable=True))
    op.add_column('residential_complex', sa.Column('commercial_area', sa.DECIMAL(), nullable=True))
    op.drop_column('residential_complex', 'commercials_area')
    op.drop_column('residential_complex', 'apartments_area')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residential_complex', sa.Column('apartments_area', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('residential_complex', sa.Column('commercials_area', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('residential_complex', 'commercial_area')
    op.drop_column('residential_complex', 'apartment_area')
    # ### end Alembic commands ###
