"""

Revision ID: 82bfe7a7a5ff
Revises: 11b90abc3fd1
Create Date: 2025-12-21 18:02:23.080665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bfe7a7a5ff'
down_revision: Union[str, Sequence[str], None] = '11b90abc3fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('kz_description', sa.String(), nullable=True))
    op.add_column('apartment', sa.Column('en_description', sa.String(), nullable=True))
    op.add_column('apartment', sa.Column('ru_description', sa.String(), nullable=True))
    op.add_column('apartment', sa.Column('ru_short_description', sa.String(length=300), nullable=True))
    op.add_column('apartment', sa.Column('kz_short_description', sa.String(length=300), nullable=True))
    op.add_column('apartment', sa.Column('en_short_description', sa.String(length=300), nullable=True))
    op.drop_column('apartment', 'description')
    op.drop_column('apartment', 'short_description')
    op.add_column('building', sa.Column('kz_description', sa.String(), nullable=True))
    op.add_column('building', sa.Column('en_description', sa.String(), nullable=True))
    op.add_column('building', sa.Column('ru_description', sa.String(), nullable=True))
    op.add_column('building', sa.Column('ru_short_description', sa.String(length=300), nullable=True))
    op.add_column('building', sa.Column('kz_short_description', sa.String(length=300), nullable=True))
    op.add_column('building', sa.Column('en_short_description', sa.String(length=300), nullable=True))
    op.drop_column('building', 'description')
    op.drop_column('building', 'short_description')
    op.add_column('commercial_unit', sa.Column('kz_description', sa.String(), nullable=True))
    op.add_column('commercial_unit', sa.Column('en_description', sa.String(), nullable=True))
    op.add_column('commercial_unit', sa.Column('ru_description', sa.String(), nullable=True))
    op.add_column('commercial_unit', sa.Column('ru_short_description', sa.String(length=300), nullable=True))
    op.add_column('commercial_unit', sa.Column('kz_short_description', sa.String(length=300), nullable=True))
    op.add_column('commercial_unit', sa.Column('en_short_description', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commercial_unit', 'en_short_description')
    op.drop_column('commercial_unit', 'kz_short_description')
    op.drop_column('commercial_unit', 'ru_short_description')
    op.drop_column('commercial_unit', 'ru_description')
    op.drop_column('commercial_unit', 'en_description')
    op.drop_column('commercial_unit', 'kz_description')
    op.add_column('building', sa.Column('short_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('building', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('building', 'en_short_description')
    op.drop_column('building', 'kz_short_description')
    op.drop_column('building', 'ru_short_description')
    op.drop_column('building', 'ru_description')
    op.drop_column('building', 'en_description')
    op.drop_column('building', 'kz_description')
    op.add_column('apartment', sa.Column('short_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('apartment', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('apartment', 'en_short_description')
    op.drop_column('apartment', 'kz_short_description')
    op.drop_column('apartment', 'ru_short_description')
    op.drop_column('apartment', 'ru_description')
    op.drop_column('apartment', 'en_description')
    op.drop_column('apartment', 'kz_description')
    # ### end Alembic commands ###
