"""

Revision ID: 88106df8f761
Revises: 8189fa6e13cb
Create Date: 2025-10-03 07:05:41.153565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88106df8f761'
down_revision: Union[str, Sequence[str], None] = '8189fa6e13cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('residential_complex', 'apartment_area',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('residential_complex', 'commercial_area',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('residential_complex', 'commercial_area',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('residential_complex', 'apartment_area',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
