"""add_infrastructure_table

Revision ID: 8929eca03e26
Revises: d4664e61396f
Create Date: 2025-12-14 21:10:12.612017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8929eca03e26'
down_revision: Union[str, Sequence[str], None] = 'd4664e61396f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residential_complex_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('education', 'shopping', 'parks', 'health', 'transport', 'sports', 'restaurants', 'services', name='infrastructure_category'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('distance', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['residential_complex_id'], ['residential_complex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infrastructure')
    # ### end Alembic commands ###
