"""

Revision ID: bcc1c1d97e27
Revises: 13b39961acaa
Create Date: 2025-11-03 17:58:57.039824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc1c1d97e27'
down_revision: Union[str, Sequence[str], None] = '13b39961acaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('loyalty_point', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'loyalty_point')
    # ### end Alembic commands ###
