"""

Revision ID: e785fae8030b
Revises: bcc1c1d97e27
Create Date: 2025-12-06 16:54:39.449582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e785fae8030b'
down_revision: Union[str, Sequence[str], None] = 'bcc1c1d97e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residential_complex', sa.Column('min_area', sa.DECIMAL(), nullable=True))
    op.add_column('residential_complex', sa.Column('min_price', sa.DECIMAL(), nullable=True))
    op.add_column('residential_complex', sa.Column('construction_end', sa.Date(), nullable=True))
    op.add_column('residential_complex', sa.Column('main_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residential_complex', 'main_image')
    op.drop_column('residential_complex', 'construction_end')
    op.drop_column('residential_complex', 'min_price')
    op.drop_column('residential_complex', 'min_area')
    # ### end Alembic commands ###
