"""init tables

Revision ID: f143957bc9e5
Revises: 
Create Date: 2025-09-26 12:14:26.731840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f143957bc9e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.Enum('commercial', 'apartment', 'residential_complex', 'building', name='object_type'), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('upload_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residential_complex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('block_counts', sa.Integer(), nullable=True),
    sa.Column('playground_area', sa.DECIMAL(), nullable=True),
    sa.Column('apartments_area', sa.DECIMAL(), nullable=True),
    sa.Column('commercials_area', sa.DECIMAL(), nullable=True),
    sa.Column('parking_area', sa.DECIMAL(), nullable=True),
    sa.Column('landing_area', sa.DECIMAL(), nullable=True),
    sa.Column('material', sa.Enum('brick', 'monolith', 'panel', 'block', 'mixed', name='material'), nullable=True),
    sa.Column('city', sa.Enum('almaty', 'astana', 'shymkent', 'karaganda', 'aktobe', 'taraz', 'pavlodar', 'oskemen', 'semey', 'kostanay', 'kyzylorda', 'atyrau', 'oral', 'petropavl', 'turkistan', name='city'), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('longitude', sa.DECIMAL(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(), nullable=True),
    sa.Column('has_security', sa.Boolean(), nullable=True),
    sa.Column('building_class', sa.Enum('economic', 'comfort', 'comfort_plus', 'business', 'luxury', name='building_class'), nullable=True),
    sa.Column('building_status', sa.Enum('project', 'under_construction', 'completed', name='building_status'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('city', sa.Enum('almaty', 'astana', 'shymkent', 'karaganda', 'aktobe', 'taraz', 'pavlodar', 'oskemen', 'semey', 'kostanay', 'kyzylorda', 'atyrau', 'oral', 'petropavl', 'turkistan', name='city'), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', 'consumer', name='role'), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('status_of_user', sa.Enum('bronze', 'silver', 'gold', 'none', name='status_of_user'), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residential_complex_id', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('floor_count', sa.Integer(), nullable=True),
    sa.Column('apartments_count', sa.Integer(), nullable=True),
    sa.Column('commercials_count', sa.Integer(), nullable=True),
    sa.Column('parking_count', sa.Integer(), nullable=True),
    sa.Column('gross_area', sa.DECIMAL(), nullable=True),
    sa.Column('elevators_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('project', 'under_construction', 'completed', name='status'), nullable=True),
    sa.Column('construction_start', sa.Date(), nullable=True),
    sa.Column('construction_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['residential_complex_id'], ['residential_complex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.Enum('commercial', 'apartment', 'residential_complex', 'building', name='object_type'), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.Enum('booking', 'purchase', name='order_type'), nullable=True),
    sa.Column('object_type', sa.Enum('commercial', 'apartment', 'residential_complex', 'building', name='object_type'), nullable=True),
    sa.Column('total_price', sa.DECIMAL(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('payment_type', sa.Enum('cash', 'card', 'mortgage', 'installment', 'bank_transfer', name='payment_type'), nullable=True),
    sa.Column('booking_deposit', sa.DECIMAL(), nullable=True),
    sa.Column('booking_expiration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'offering', 'cancelled', 'completed', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residential_complex_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['residential_complex_id'], ['residential_complex.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.DECIMAL(), nullable=True),
    sa.Column('loyalty_points', sa.DECIMAL(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('apartment_area', sa.DECIMAL(), nullable=True),
    sa.Column('apartment_type', sa.Enum('studio', 'one_bedroom', 'two_bedroom', 'three_bedroom', 'penthouse', name='apartment_type'), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=True),
    sa.Column('bathroom_count', sa.Integer(), nullable=True),
    sa.Column('kitchen_area', sa.DECIMAL(), nullable=True),
    sa.Column('ceiling_height', sa.DECIMAL(), nullable=True),
    sa.Column('finishing_type', sa.Enum('black_box', 'white_box', 'finished', 'turnkey', name='finishing_type'), nullable=True),
    sa.Column('price_per_sqr', sa.DECIMAL(), nullable=True),
    sa.Column('total_price', sa.DECIMAL(), nullable=True),
    sa.Column('status', sa.Enum('free', 'booked', 'sold', name='status'), nullable=True),
    sa.Column('orientation', sa.Enum('north', 'south', 'east', 'west', 'north_east', 'south_east', 'north_west', 'south_west', 'north_south', 'east_west', name='direction'), nullable=True),
    sa.Column('isCorner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commercial_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('space_area', sa.DECIMAL(), nullable=True),
    sa.Column('ceiling_height', sa.DECIMAL(), nullable=True),
    sa.Column('finishing_type', sa.Enum('black_box', 'white_box', 'finished', 'turnkey', name='finishing_type'), nullable=True),
    sa.Column('price_per_sqr', sa.DECIMAL(), nullable=True),
    sa.Column('total_price', sa.DECIMAL(), nullable=True),
    sa.Column('status', sa.Enum('free', 'booked', 'sold', name='status'), nullable=True),
    sa.Column('orientation', sa.Enum('north', 'south', 'east', 'west', 'north_east', 'south_east', 'north_west', 'south_west', 'north_south', 'east_west', name='direction'), nullable=True),
    sa.Column('isCorner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('deposit', 'withdrawal', 'purchase', 'refund', 'loyalty_earned', 'loyalty_spent', 'bonus', 'penalty', 'transfer_in', 'transfer_out', name='transaction_type'), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('balance_before', sa.DECIMAL(), nullable=True),
    sa.Column('balance_after', sa.DECIMAL(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['user_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transaction')
    op.drop_table('commercial_unit')
    op.drop_table('apartment')
    op.drop_table('user_wallet')
    op.drop_table('review')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('order')
    op.drop_table('favorites')
    op.drop_table('building')
    op.drop_table('users')
    op.drop_table('residential_complex')
    op.drop_table('image')
    # ### end Alembic commands ###
